### PR TITLE
Integrating Filters list in wsynphot/docs

### PR DESCRIPTION
**Pull request by jaladh-singhal**
This auto-generates filters list & curves while building the documentation from the dataset (hd5 file)

### CODE REVIEW

**Comment by wkerzendorf** [comment]
I think we should autogenerate the html files on build and not include 81 files here.

**Comment by jaladh-singhal** [comment]
OK I'll try to achieve that. It means, we're continuing this, right?

**Comment by wkerzendorf** [comment]
I think you want to make a new PR and abandon this.

**Comment by jaladh-singhal** [comment]
@wkerzendorf  I've checked it is working absolutely fine.

If you want a refined commit history, then I can close this and create a new one?

**Comment by wkerzendorf** [comment]
@jaladh-singhal yes - you can make it work absolutely fine - I think it is still better to start a new one that has not 81 files changed. It makes it easier for me to look at your work.

**Comment by jaladh-singhal** [comment]
@wkerzendorf OK, I'm creating a new one!

Although the next commit I was about to commit in this PR was to fix that 81 files issue only.

**Pull request closed without merging**
